In [2]:
import os
from dotenv import load_dotenv

In [3]:
os.environ["GOOGLE_API_KEY"] =os.getenv("GOOGLE_API_KEY")

In [4]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings

f:\sourab\modern_route\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
from sentence_transformers import SentenceTransformer

In [6]:
open_source_embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

In [7]:
text = 'machine'

In [8]:
embedding = open_source_embedding_model.encode(text)

In [9]:
embedding

array([-7.21354410e-02,  2.84874551e-02, -1.17706126e-02,  1.98008772e-02,
       -4.34783362e-02, -3.14590000e-02,  1.49604762e-02,  2.88986880e-03,
        3.24487640e-03, -3.39518748e-02,  1.04992324e-02, -1.02071995e-02,
        7.77680576e-02, -7.65563995e-02, -1.39956153e-03, -2.10193056e-03,
        1.71924122e-02, -6.33648485e-02, -2.81336661e-02, -5.86969182e-02,
       -3.29725407e-02,  1.02291368e-02, -6.45695478e-02,  1.98799595e-02,
       -1.06031718e-02,  1.04793400e-01, -3.81070636e-02,  5.03518507e-02,
        2.06003450e-02, -1.30085513e-01, -2.18260307e-02,  4.07632394e-03,
        6.23156593e-05,  2.95541510e-02,  3.27022821e-02, -1.54474946e-02,
        3.09898946e-02, -3.76024656e-02,  1.37064802e-02, -5.00646792e-02,
        2.30320916e-02, -7.93177933e-02, -8.26479936e-06, -1.97606366e-02,
        7.49427527e-02,  1.02477886e-01,  6.01520436e-03, -3.98588106e-02,
        5.47021888e-02,  3.11047509e-02, -1.16405949e-01, -7.04230592e-02,
        6.45304993e-02,  

In [10]:
len(embedding)

384

In [11]:
embedding.shape

(384,)

In [12]:
sentence =  "How to reduce heart disease risk?"

In [13]:
embedding = open_source_embedding_model.encode(sentence)

In [14]:
embedding.shape

(384,)

In [15]:
paragraph = """
Machine learning is a field of artificial intelligence that focuses on building systems 
that learn from data. It is widely used in applications like recommendation systems, 
image recognition, and natural language processing.
"""

In [16]:
embedding = open_source_embedding_model.encode(paragraph)

In [17]:
embedding.shape

(384,)

In [18]:
embedding

array([-2.78186798e-02, -6.40660478e-03,  3.68497372e-02,  2.21404689e-03,
        2.55084336e-02,  1.34023083e-02,  6.45566639e-03, -3.05500831e-02,
       -6.01915084e-02, -2.28518229e-02, -7.05490112e-02,  1.97643787e-02,
        5.54116145e-02, -3.38736176e-02, -9.74510424e-03,  4.72750515e-02,
       -1.58115178e-02, -1.64723676e-02, -6.00375310e-02, -7.00236335e-02,
        2.54246928e-02, -5.45074092e-03, -7.51983076e-02,  1.57804154e-02,
       -1.62698328e-02,  5.30246682e-02,  6.29331246e-02,  1.47748403e-02,
       -1.32339094e-02,  5.44597255e-03,  2.14248747e-02, -3.44793163e-02,
        1.16899069e-02,  4.35766652e-02, -4.42826711e-02,  5.05335182e-02,
       -2.66971309e-02,  5.36211208e-03,  7.96867721e-03, -1.89669728e-02,
       -6.25875518e-02, -7.47380704e-02,  6.55541150e-03, -6.77178428e-03,
        1.26145527e-01,  1.28760204e-01, -7.31318668e-02, -9.79881287e-02,
        8.16384214e-04,  1.73747130e-02, -1.05541214e-01,  1.18358172e-02,
       -1.23240715e-02,  

In [19]:
from transformers import CLIPModel, CLIPProcessor

In [20]:
from PIL import Image

In [21]:
image = Image.open("F:\sourab\modern_route\encoding and embeddings\sample_image.jpg")

In [22]:
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.


In [23]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

In [24]:
input = processor(images=image, return_tensors="pt")

In [25]:
import torch
with torch.no_grad():
    image_embedding = model.get_image_features(**input)

In [26]:
image_embedding

tensor([[-6.0670e-02,  1.3432e-01, -1.3355e-01, -2.3871e-01, -1.2294e-01,
         -4.3371e-01, -2.9441e-01,  3.3715e-01,  6.3663e-01, -2.7596e-02,
         -2.6382e-01,  2.6779e-01, -1.0666e-01, -7.6754e-02, -3.1785e-01,
          4.5438e-01,  3.4414e-01,  2.8692e-01, -1.7968e-01,  6.1431e-03,
          2.2777e-01,  7.8303e-02,  1.7582e-02, -3.1674e-01, -5.0411e-01,
          2.2160e-01,  1.9401e-01, -2.3551e-01, -5.0639e-01, -1.7114e-01,
          8.8795e-02, -1.5341e-01, -2.7781e-01, -3.8883e-02, -3.2975e-01,
          9.9825e-02,  2.4963e-02,  5.9490e-01, -1.7074e-01, -2.1389e+00,
         -5.1749e-01, -1.6407e-01,  1.4265e-01, -2.2048e-01, -8.6635e-02,
          2.8053e-01, -7.1026e-04, -3.4677e-01, -1.5826e-01,  3.9561e-01,
          2.0012e-01,  7.0539e-02, -2.2942e-02, -4.6413e-01,  1.4735e-01,
         -8.3080e-02,  3.2927e-01,  2.8091e-01, -6.5418e-02,  1.4803e-01,
          1.1371e-01, -5.5497e-01, -1.1847e-01,  3.6914e-01, -2.9678e-01,
          5.2321e-01, -3.0791e-01,  3.

#### Semantic Search (Similarity Search)
1. Dot Product
2. Cosine Sim
3. Eculidean Distance(L2)

In [27]:
import numpy as np

def dot_product(a, b):
    return np.dot(a, b)

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def euclidean_distance(a, b):
    a = np.array(a)
    b = np.array(b)
    return np.linalg.norm(a - b)

print("=== Cosine Similarity (Higher is better) ===")
print("Range: -1 to 1")

print("\n=== Dot Product (Higher is better) ===")
print("Range: -∞ to +∞ (depends on vector magnitude)")

print("\n=== Euclidean Distance (Lower is better) ===")
print("Range: 0 to +∞")

=== Cosine Similarity (Higher is better) ===
Range: -1 to 1

=== Dot Product (Higher is better) ===
Range: -∞ to +∞ (depends on vector magnitude)

=== Euclidean Distance (Lower is better) ===
Range: 0 to +∞


In [28]:
query = "How to reduce heart disease risk?"

documents = [
    "Eating fiber reduces heart risk.",
    "Fruits and vegetables lower cardiovascular disease chances.",
    "Buying a new car improves driving comfort.",
    "Regular exercise improves heart health."
]

In [29]:
google_embeddings_model = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

In [30]:
query_embeddings = google_embeddings_model.embed_query(query)
doc_embeddings = google_embeddings_model.embed_documents(documents)

In [31]:
len(query_embeddings)

3072

In [32]:
len(doc_embeddings)

4

In [33]:
result = []

In [34]:
for doc, doc_emb in zip(documents, doc_embeddings):
    result.append({
        "query": query,
        "document": doc,
        "cosine":cosine_similarity(query_embeddings, doc_emb),
        "dot_product": dot_product(query_embeddings, doc_emb),
        "euclidean": euclidean_distance(query_embeddings, doc_emb)
    })

In [35]:
result

[{'query': 'How to reduce heart disease risk?',
  'document': 'Eating fiber reduces heart risk.',
  'cosine': 0.7395238839381588,
  'dot_product': 0.739523906997596,
  'euclidean': 0.721770218537545},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Fruits and vegetables lower cardiovascular disease chances.',
  'cosine': 0.7132289221700369,
  'dot_product': 0.7132289415495634,
  'euclidean': 0.7573256705301548},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Buying a new car improves driving comfort.',
  'cosine': 0.5761824193919591,
  'dot_product': 0.5761824550973115,
  'euclidean': 0.9206710670717551},
 {'query': 'How to reduce heart disease risk?',
  'document': 'Regular exercise improves heart health.',
  'cosine': 0.7141669909372164,
  'dot_product': 0.7141670824821801,
  'euclidean': 0.7560860343930161}]

### **Keyword Search**

In [36]:
documents

['Eating fiber reduces heart risk.',
 'Fruits and vegetables lower cardiovascular disease chances.',
 'Buying a new car improves driving comfort.',
 'Regular exercise improves heart health.']

In [37]:
query

'How to reduce heart disease risk?'

In [38]:
from collections import Counter

In [39]:
query.lower().replace("?","").split()

['how', 'to', 'reduce', 'heart', 'disease', 'risk']

In [40]:
documents[0]

'Eating fiber reduces heart risk.'

In [42]:
query_words = query.lower().replace(".","").split()
doc_words = documents[0].lower().replace(".","").split()

In [43]:
query_words

['how', 'to', 'reduce', 'heart', 'disease', 'risk?']

In [44]:
doc_words

['eating', 'fiber', 'reduces', 'heart', 'risk']

In [45]:
doc_count = Counter(doc_words)

In [46]:
for word in query_words:
    print(f"{word}: {doc_count[word]}")

how: 0
to: 0
reduce: 0
heart: 1
disease: 0
risk?: 0


In [47]:
score = sum(doc_count[w] for w in query_words)

In [48]:
score

1

#### Score = number of matching words

In [49]:
def keyword_search(query, document):
    query_words = query.lower().replace("?","").split()
    result=[]

    for doc in document:
        doc_words = doc.lower().replace(".","").split()
        doc_count = Counter(doc_words)

        score = sum(doc_count[w] for w in query_words)
        result.append((doc, score))
    return sorted(result, key=lambda x: x[1], reverse=True)

In [50]:
keyword_result = keyword_search(query, documents)

In [52]:
keyword_result

[('Eating fiber reduces heart risk.', 2),
 ('Fruits and vegetables lower cardiovascular disease chances.', 1),
 ('Regular exercise improves heart health.', 1),
 ('Buying a new car improves driving comfort.', 0)]